# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_number', models.BigIntegerField()),
                ('express_company', models.CharField(max_length=10)),
                ('recipient', models.CharField(max_length=5)),
                ('recipient_phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Express_delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_number', models.BigIntegerField()),
                ('express_company', models.CharField(max_length=10)),
                ('recipient', models.CharField(max_length=5)),
                ('recipient_phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=10)),
                ('sender', models.CharField(max_length=5)),
                ('sender_phone', models.BigIntegerField()),
            ],
        ),
    ]
