# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=16)),
            ],
        ),
    ]
