# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='express',
            name='shelfID',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='express_delivery',
            name='shelfID',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
