# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170918_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='express_delivery',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
