# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170920_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='status',
            field=models.CharField(choices=[('0', '未取件'), ('1', '已取件'), ('2', '问题件'), ('3', '拒收'), ('4', '无人领取'), ('5', '其他')], max_length=1),
        ),
        migrations.AlterField(
            model_name='express_delivery',
            name='status',
            field=models.CharField(choices=[('0', '未揽件'), ('1', '已揽件'), ('2', '已发出'), ('3', '其他')], max_length=1),
        ),
    ]
